### ISSUE TITLE
[BUG] Error while setting token

### ISSUE THREAD

**Issue by momonunu** [mini-bomba/StreamChatMod#12]
**Describe the bug**
When I set the token via /twitch token or /twitch settoken xxxx

**Expected behavior**
Twitch token should be set and /twitch enable should work

**Actual behavior**
Error while executing commands. /twitch enable says `An important action for the Twitch Chat is currently pending, please wait.`

**Logs & Screenshots**
`[15:06:01] [Client thread/INFO]: [CHAT] §aTwitch token was successfully updated!
[15:06:01] [Client thread/INFO]: [CHAT] §7Restarting Twitch Chat...
[15:06:01] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: java.util.ConcurrentModificationException: An important async action is currently scheduled!
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at me.mini_bomba.streamchatmod.StreamChatMod.asyncTwitchAction(StreamChatMod.java:279)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at me.mini_bomba.streamchatmod.StreamChatMod.asyncRestartTwitch(StreamChatMod.java:322)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at me.mini_bomba.streamchatmod.commands.subcommands.TwitchSetTokenSubcommand.processSubcommand(TwitchSetTokenSubcommand.java:64)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at me.mini_bomba.streamchatmod.commands.TwitchCommand.func_71515_b(TwitchCommand.java:104)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:72)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:446)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:437)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java:111)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:578)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:91)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at gg.essential.loader.stage2.EssentialLoader.addToClasspath(EssentialLoader.java:86)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at gg.essential.loader.stage2.EssentialLoaderBase.addToClasspath(EssentialLoaderBase.java:320)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:135)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:41)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:111)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:34)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at club.sk1er.oldanimations.loader.AnimationsTweak.<init>(AnimationsTweak.java:19)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at java.lang.Class.newInstance(Class.java:442)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[15:06:01] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Environment information**
 - OS: Mac
 - Forge version: 11.15.1.2318
 - Mod version: StreamChatMod-git_80489715-for-1.8.9.jar but also happens with the one before it.
 - Other installed mods: Normal Skyblock mods. ` Mod signature data
[15:01:06] [Client thread/DEBUG]:  	Valid Signatures:
[15:01:06] [Client thread/DEBUG]: 		(e3c3d50c7c986df74c645c0ac54639741c90a557) FML	(Forge Mod Loader	8.0.99.99)	forge-1.8.9-11.15.1.2318-1.8.9.jar
[15:01:06] [Client thread/DEBUG]: 		(e3c3d50c7c986df74c645c0ac54639741c90a557) Forge	(Minecraft Forge	11.15.1.2318)	forge-1.8.9-11.15.1.2318-1.8.9.jar
[15:01:06] [Client thread/DEBUG]: 		(0422b7d5e421b108a16a2cc652eb05b5f35e9546) SkyblockExtras	(SkyblockExtras	2.1.9.1)	SkyblockExtras-2.1.9.1.jar
[15:01:06] [Client thread/DEBUG]:  	Missing Signatures:
[15:01:06] [Client thread/DEBUG]: 		mcp	(Minecraft Coder Pack	9.19)	minecraft.jar
[15:01:06] [Client thread/DEBUG]: 		essential	(Essential	1.0.0)	Essential (forge_1.8.9).jar
[15:01:06] [Client thread/DEBUG]: 		autotip	(Autotip	3.0.1)	Autotip-3.0.1 [1.8-1.12.2].jar
[15:01:06] [Client thread/DEBUG]: 		BazaarNotifier	(BazaarNotifier	1.4.7)	BazaarNotifier-1.4.7.jar
[15:01:06] [Client thread/DEBUG]: 		ct.js	(ChatTriggers	1.3.2)	ctjs-1.3.2-1.8.9.jar
[15:01:06] [Client thread/DEBUG]: 		dungeonrooms	(Dungeon Rooms Mod	3.2.4)	Dungeon_Rooms-3.2.4.jar
[15:01:06] [Client thread/DEBUG]: 		notenoughupdates	(NotEnoughUpdates	2.0.0-REL)	NotEnoughUpdates-2.0.0.jar
[15:01:06] [Client thread/DEBUG]: 		sk1er_old_animations	(Sk1er Old Animations	0.2.0)	OldAnimations_1.0.0_-_beta_9.jar
[15:01:06] [Client thread/DEBUG]: 		patcher	(Patcher	1.7.0)	Patcher-1.7.0 (1.8.9).jar
[15:01:06] [Client thread/DEBUG]: 		text_overflow_scroll	(Scrollable Tooltips	1.4.0)	Scrollable Tooltips-1.4 (1.8.9).jar
[15:01:06] [Client thread/DEBUG]: 		skyblockaddons	(SkyblockAddons	1.6.1)	SkyblockAddons-1.6.1-for-MC-1.8.9.jar
[15:01:06] [Client thread/DEBUG]: 		skytils	(Skytils	1.0.9-pre1.1)	Skytils-1.0.9-pre1.1.jar
[15:01:06] [Client thread/DEBUG]: 		streamchatmod	(streamchatmod	1.4.0)	StreamChatMod-git_80489715-for-1.8.9.jar`

note: if you are using additional mods, please make sure this bug can still be replicated without them.
if this bug can only be replicated with additional mods, please use the "Incompatibility report" template instead.

**Comment by mini-bomba** [comment]
I cannot really replicate this issue, but I have a suspicion of what might have caused this.
I've just pushed a [commit](https://github.com/mini-bomba/StreamChatMod/commit/fb09a1e4c48fd194b2a7c6991d52b220edb85ea3) that should ensure the "important action in progress" flag always gets reset, even if the important action throws an error.
It should be in the prereleases soon, please confirm that this fixes this issue.
